server:
  port: 8083

spring:
  application:
    name: auth-service
  redis:
    host: localhost
    port: 6379

dubbo:
  application:
    name: auth-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://localhost:2181

jwt:
  expiration: 86400000
  secret: your-secret-key-should-be-at-least-256-bits-long