server:
  port: 8084

spring:
  redis:
    host: localhost
    port: 6379

jwt:
  secret: your-secret-key-should-be-at-least-256-bits-long
  expiration: 86400000

dubbo:
  application:
    name: api-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://localhost:2181
